feat(profile): MP-412 Wiring Profile Page
Nub-en-Nuber/NuberJam-Android pull request #151
Opened 2023-11-27 03:23 UTC by args06

## Update Items
- [x] [[MP-412]](https://args06.atlassian.net/jira/software/projects/MP/boards/5?selectedIssue=MP-412) Wiring UI, Show Snackbar, Get Account from DataStore

## Summary Description
- Wiring profile UI based on datastore data
- Prepare all action click and snack bar functions on the profile page

## Problems
- There is missing API data, so the default value of the profile photo does not appear

## Screenshot (Optional)
### After
- 
![image](https://github.com/Nub-en-Nuber/NuberJam-Android/assets/49654730/447b28e7-077f-463c-a102-0a9765fd6314)

## *Type of Change
- [ ] docs: Documentation only changes, README.md, Wiki
- [x] feat: A new feature
- [ ] refactor: A code change that neither fixes a bug nor adds a feature
- [ ] test: Anything related to unit/integration testing
- [ ] revert: Revert a commit

## Type of Scope
- [ ] album: Changes that affect user packages
- [ ] music: Changes that affect music packages
- [x] account: Changes that affect account packages
- [ ] favorite: Changes that affect favorite packages
- [ ] playlist: Changes that affect playlist packages
- [ ] playlist-detail: Changes that affect playlist-detail packages
- [ ] music-artist: Changes that affect music-artist packages
- [ ] general: all stuff except above

2023-11-27 12:09 UTC, RTAgung requested changes

2023-11-27 12:09 UTC, RTAgung commented on app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
> +            Glide.with(requireActivity()).load(account.photo).into(imvProfile)
I think give the error drawable and placeholder drawable will be better

2023-11-27 12:11 UTC, args06 commented on app/src/main/java/com/example/nuberjam/ui/main/profile/ProfileFragment.kt
> +            Glide.with(requireActivity()).load(account.photo).into(imvProfile)
So we need to use direct placeholder image in AS?  Because we need more than 1 default photo like Profile, album, playlist, music

2023-11-28 12:09 UTC, RTAgung approved these changes

2023-11-28 12:10 UTC, merged